In [2]:
import mysql.connector

connection_mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="wp-ecommerce"
)

In [7]:
def get_product_name(connection_mydb, product_id):

    cursor = connection_mydb.cursor(dictionary=True)
    sql = "SELECT post_title FROM wp_posts WHERE ID=(%s)"
    id = (product_id,)
    
    cursor.execute(sql, id)
    results = cursor.fetchall()
    if len(results) > 0:
        return results[0]["post_title"]
  # return "unkown"
    else:
        print ("unkown")

get_product_name(connection_mydb, 55945)

"بنطال قماش رجالي-أزرق-Levi's"

In [8]:
get_product_name(connection_mydb, 99999)

unkown

In [11]:
import pandas as pd
def df_associated_products(connection_mydb):
    df = pd.DataFrame(columns=[0,1,2,3,4,5,6,7,8,9])
    
    cursor = connection_mydb.cursor(dictionary=True)
    
    sql = "SELECT * FROM wp_wc_order_stats order by order_id "
    cursor.execute(sql)
    results_orders = cursor.fetchall()

    for order in results_orders:
        order_id = order["order_id"]
        sql = "SELECT * FROM wp_wc_order_product_lookup where order_id=(%s)"
        id = (order_id,)
        cursor.execute(sql, id)
        
        results_products = cursor.fetchall()

        products_list = []
        for product in results_products:
            product_id = product["product_id"]
            if product_id > 0:
                products_list.append(product_id)
        if len(products_list) > 1:
            df = pd.concat([df, pd.DataFrame([products_list])], ignore_index=True)
    return df

df = df_associated_products(connection_mydb)
df

          0      1      2      3      4    5    6    7    8    9
0     55959  55979  56265  55968    NaN  NaN  NaN  NaN  NaN  NaN
1     55945  55947  56108  56261  55973  NaN  NaN  NaN  NaN  NaN
2     55890  55931  56064  56297  55898  NaN  NaN  NaN  NaN  NaN
3     56007  55982  56152  56286  55981  NaN  NaN  NaN  NaN  NaN
4     55884  55886  56082  56288  55879  NaN  NaN  NaN  NaN  NaN
...     ...    ...    ...    ...    ...  ...  ...  ...  ...  ...
2540  56214  56247  56238  56235    NaN  NaN  NaN  NaN  NaN  NaN
2541  56354  56341    NaN    NaN    NaN  NaN  NaN  NaN  NaN  NaN
2542  55958  56005    NaN    NaN    NaN  NaN  NaN  NaN  NaN  NaN
2543  56007  56115  55976    NaN    NaN  NaN  NaN  NaN  NaN  NaN
2544  56200  56202    NaN    NaN    NaN  NaN  NaN  NaN  NaN  NaN

[2545 rows x 10 columns]

In [14]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\hp\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 578.7 kB/s eta 0:00:02
   --------------- ------------------------ 0.5/1.4 MB 578.7 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 684.4 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 684.4 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 684.4 kB/s eta 0:00:01
   ------------------------------- -------- 1.0/1.4 MB 535.4 kB/s eta 0:00:01
   ------------------------------- -------- 1.0/1.4 MB 535.4 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 581.4 kB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4

In [15]:
def prepare_transactions(df):
    df = df.T
    transactions = df.apply(lambda x: x.dropna().tolist())
    transactions_list = transactions.values.tolist()
    
    from mlxtend.preprocessing import TransactionEncoder

    te = TransactionEncoder()
    te_model = te.fit(transactions_list)
    rows = te_model.transform(transactions_list)

    df_transactions = pd.DataFrame(rows, columns=te_model.columns_)
    return df_transactions

df_transactions = prepare_transactions(df)
df_transactions

,55868,55869,55870,55873,55874,55876,55877,55878,55879,55881,...,56345,56347,56350,56351,56354,56355,56358,56359,56360,56363
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2540,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2541,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2542,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2543,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2544,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
def generate_association_rules(df_transactions, min_support, min_confidence):
    
    from mlxtend.frequent_patterns import apriori
    
    frequent_itemsets = apriori(df_transactions, min_support=min_support, use_colnames=True)
    
    from mlxtend.frequent_patterns import association_rules
    
    rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_confidence)
    
    rules = rules.sort_values(['confidence'], ascending=[False])
    
    return rules

rules = generate_association_rules(df_transactions, 0.004, 0.1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
15,(56235),(56193),0.009430,0.031434,0.004322,0.458333,14.580729,1.0,0.004026,1.788122,0.940283,0.118280,0.440754,0.297917
28,(56209),(56238),0.012181,0.036149,0.005501,0.451613,12.492987,1.0,0.005061,1.757610,0.931299,0.128440,0.431046,0.301893
51,(56323),(56305),0.010609,0.016896,0.004322,0.407407,24.112834,1.0,0.004143,1.658988,0.968806,0.186441,0.397223,0.331611
4,(56179),(56238),0.017289,0.036149,0.006287,0.363636,10.059289,1.0,0.005662,1.514623,0.916433,0.133333,0.339769,0.268775
1,(56179),(56218),0.017289,0.029862,0.006287,0.363636,12.177033,1.0,0.005771,1.524502,0.934026,0.153846,0.344048,0.287081
20,(56195),(56238),0.015717,0.036149,0.005501,0.350000,9.682065,1.0,0.004933,1.482847,0.911035,0.118644,0.325622,0.251087
40,(56227),(56228),0.014931,0.031041,0.004715,0.315789,10.173218,1.0,0.004252,1.416170,0.915370,0.114286,0.293870,0.233844
8,(56188),(56228),0.017682,0.031041,0.005501,0.311111,10.022504,1.0,0.004952,1.406553,0.916429,0.127273,0.289042,0.244163
35,(56245),(56217),0.014145,0.033399,0.004322,0.305556,9.148693,1.0,0.003850,1.391906,0.903475,0.100000,0.281561,0.217484
42,(56232),(56228),0.015717,0.031041,0.004715,0.300000,9.664557,1.0,0.004227,1.384227,0.910845,0.112150,0.277575,0.225949
19,(56195),(56217),0.015717,0.033399,0.004322,0.275000,8.233824,1.0,0.003797,1.333243,0.892578,0.096491,0.249949,0.202206
50,(56305),(56323),0.016896,0.010609,0.004322,0.255814,24.112834,1.0,0.004143,1.329494,0.975002,0.186441,0.247834,0.331611
2,(56179),(56228),0.017289,0.031041,0.004322,0.250000,8.053797,1.0,0.003786,1.291945,0.891244,0.098214,0.225973,0.194620
49,(56247),(56238),0.023576,0.036149,0.005501,0.233333,6.454710,1.0,0.004649,1.257197,0.865479,0.101449,0.204579,0.192754
7,(56183),(56199),0.018861,0.022397,0.004322,0.229167,10.232091,1.0,0.003900,1.268242,0.919613,0.117021,0.211507,0.211075
17,(56247),(56193),0.023576,0.031434,0.005108,0.216667,6.892708,1.0,0.004367,1.236467,0.875561,0.102362,0.191244,0.189583
44,(56234),(56228),0.025540,0.031041,0.005501,0.215385,6.938656,1.0,0.004708,1.234947,0.878312,0.107692,0.190249,0.196300
46,(56228),(56238),0.031041,0.036149,0.006680,0.215190,5.952807,1.0,0.005558,1.228132,0.858666,0.110390,0.185755,0.199986
0,(56218),(56179),0.029862,0.017289,0.006287,0.210526,12.177033,1.0,0.005771,1.244768,0.946132,0.153846,0.196637,0.287081
13,(56230),(56193),0.022790,0.031434,0.004715,0.206897,6.581897,1.0,0.003999,1.221235,0.867846,0.095238,0.181157,0.178448
11,(56228),(56193),0.031041,0.031434,0.006287,0.202532,6.443038,1.0,0.005311,1.214551,0.871857,0.111888,0.176650,0.201266
10,(56193),(56228),0.031434,0.031041,0.006287,0.200000,6.443038,1.0,0.005311,1.211198,0.872211,0.111888,0.174371,0.201266
26,(56202),(56238),0.025540,0.036149,0.005108,0.200000,5.532609,1.0,0.004185,1.204813,0.840726,0.090278,0.169996,0.170652
31,(56218),(56217),0.029862,0.033399,0.005894,0.197368,5.909443,1.0,0.004897,1.204290,0.856352,0.102740,0.169635,0.186920
6,(56199),(56183),0.022397,0.018861,0.004322,0.192982,10.232091,1.0,0.003900,1.215760,0.922939,0.117021,0.177469,0.211075
23,(56199),(56238),0.022397,0.036149,0.004322,0.192982,5.338482,1.0,0.003513,1.194337,0.831299,0.079710,0.162715,0.156274
38,(56219),(56238),0.023183,0.036149,0.004322,0.186441,5.157517,1.0,0.003484,1.184733,0.825240,0.078571,0.155928,0.153003
37,(56219),(56218),0.023183,0.029862,0.004322,0.186441,6.243310,1.0,0.003630,1.192461,0.859760,0.088710,0.161398,0.165589
47,(56238),(56228),0.036149,0.031041,0.006680,0.184783,5.952807,1.0,0.005558,1.188589,0.863217,0.110390,0.158667,0.199986
24,(56202),(56218),0.025540,0.029862,0.004715,0.184615,6.182186,1.0,0.003952,1.189791,0.860215,0.093023,0.159516,0.171255
9,(56228),(56188),0.031041,0.017682,0.005501,0.177215,10.022504,1.0,0.004952,1.193895,0.929064,0.127273,0.162405,0.244163
45,(56228),(56234),0.031041,0.025540,0.005501,0.177215,6.938656,1.0,0.004708,1.184343,0.883299,0.107692,0.155650,0.196300
30,(56217),(56218),0.033399,0.029862,0.005894,0.176471,5.909443,1.0,0.004897,1.178024,0.859485,0.102740,0.151121,0.186920
5,(56238),(56179),0.036149,0.017289,0.006287,0.173913,10.059289,1.0,0.005662,1.189598,0.934366,0.133333,0.159380,0.268775
32,(56217),(56238),0.033399,0.036149,0.005501,0.164706,4.556266,1.0,0.004294,1.153906,0.807491,0.085890,0.133378,0.158440
16,(56193),(56247),0.031434,0.023576,0.005108,0.162500,6.892708,1.0,0.004367,1.165880,0.882665,0.102362,0.142279,0.189583
25,(56218),(56202),0.029862,0.025540,0.004715,0.157895,6.182186,1.0,0.003952,1.157171,0.864048,0.093023,0.135823,0.171255
21,(56238),(56195),0.036149,0.015717,0.005501,0.152174,9.682065,1.0,0.004933,1.160949,0.930348,0.118644,0.138636,0.251087
48,(56238),(56247),0.036149,0.023576,0.005501,0.152174,6.454710,1.0,0.004649,1.151680,0.876769,0.101449,0.131703,0.192754
29,(56238),(56209),0.036149,0.012181,0.005501,0.152174,12.492987,1.0,0.005061,1.165120,0.954458,0.128440,0.141719,0.301893
33,(56238),(56217),0.036149,0.033399,0.005501,0.152174,4.556266,1.0,0.004294,1.140094,0.809796,0.085890,0.122879,0.158440
43,(56228),(56232),0.031041,0.015717,0.004715,0.151899,9.664557,1.0,0.004227,1.160572,0.925250,0.112150,0.138356,0.225949
41,(56228),(56227),0.031041,0.014931,0.004715,0.151899,10.173218,1.0,0.004252,1.161499,0.930589,0.114286,0.139044,0.233844
12,(56193),(56230),0.031434,0.022790,0.004715,0.150000,6.581897,1.0,0.003999,1.149659,0.875592,0.095238,0.130177,0.178448
36,(56218),(56219),0.029862,0.023183,0.004322,0.144737,6.243310,1.0,0.003630,1.142125,0.865680,0.088710,0.124439,0.165589
27,(56238),(56202),0.036149,0.025540,0.005108,0.141304,5.532609,1.0,0.004185,1.134814,0.849980,0.090278,0.118798,0.170652
3,(56228),(56179),0.031041,0.017289,0.004322,0.139241,8.053797,1.0,0.003786,1.141679,0.903893,0.098214,0.124097,0.194620
14,(56193),(56235),0.031434,0.009430,0.004322,0.137500,14.580729,1.0,0.004026,1.148487,0.961645,0.118280,0.129289,0.297917
34,(56217),(56245),0.033399,0.014145,0.004322,0.129412,9.148693,1.0,0.003850,1.132401,0.921471,0.100000,0.116920,0.217484
18,(56217),(56195),0.033399,0.015717,0.004322,0.129412,8.233824,1.0,0.003797,1.130595,0.908906,0.096491,0.115510,0.202206
39,(56238),(56219),0.036149,0.023183,0.004322,0.119565,5.157517,1.0,0.003484,1.109471,0.836341,0.078571,0.098670,0.153003
22,(56238),(56199),0.036149,0.022397,0.004322,0.119565,5.338482,1.0,0.003513,1.110364,0.843161,0.079710,0.099394,0.156274

In [19]:
rules = generate_association_rules(df_transactions, 0.01, 0.1)
rules.shape

(0, 14)

In [20]:
support = 0.01
confidence = 0.1
n = 0
steps = 0

while n < 2000:
    support = support/2
    steps = steps+1
    rules = generate_association_rules(df_transactions, support, confidence)
    n = rules.shape[0]
    print(" rules= ",n , ", support= ", support, ", confidence= ", confidence)

 rules=  26 , support=  0.005 , confidence=  0.1
 rules=  184 , support=  0.0025 , confidence=  0.1
 rules=  535 , support=  0.00125 , confidence=  0.1
 rules=  2460 , support=  0.000625 , confidence=  0.1

In [21]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1686,"(55914, 56286)",(55892),0.000786,0.030255,0.000786,1.0,33.051948,1.0,0.000762,inf,0.970507,0.025974,1.000000,0.512987
1739,"(55928, 55918)",(56283),0.000786,0.011788,0.000786,1.0,84.833333,1.0,0.000777,inf,0.988989,0.066667,1.000000,0.533333
1773,"(55968, 56098)",(55963),0.000786,0.020432,0.000786,1.0,48.942308,1.0,0.000770,inf,0.980338,0.038462,1.000000,0.519231
1772,"(55985, 55996)",(55961),0.000786,0.018861,0.000786,1.0,53.020833,1.0,0.000771,inf,0.981911,0.041667,1.000000,0.520833
1770,"(55961, 55985)",(55996),0.000786,0.011002,0.000786,1.0,90.892857,1.0,0.000777,inf,0.989776,0.071429,1.000000,0.535714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1523,(56317),(56333),0.007859,0.008644,0.000786,0.1,11.568182,1.0,0.000718,1.101506,0.920792,0.050000,0.092152,0.095455
205,(56260),(55888),0.007859,0.023969,0.000786,0.1,4.172131,1.0,0.000597,1.084479,0.766337,0.025316,0.077899,0.066393
1524,(56317),(56341),0.007859,0.012574,0.000786,0.1,7.953125,1.0,0.000687,1.097140,0.881188,0.040000,0.088540,0.081250
1527,(56317),(56345),0.007859,0.012967,0.000786,0.1,7.712121,1.0,0.000684,1.096704,0.877228,0.039216,0.088177,0.080303
524,(56283),(55934),0.011788,0.016896,0.001179,0.1,5.918605,1.0,0.000980,1.092338,0.840954,0.042857,0.084532,0.084884

In [22]:
def predict(rules, items, max_results= 6):
    preds = rules[rules["antecedents"] == items]
    preds = preds[["consequents", "confidence"]]
    preds.sort_values("confidence", ascending= False)
    return preds[: max_results]

In [23]:
preds = predict(rules, {56193})
preds

     consequents  confidence
1178     (56228)      0.2000
1186     (56247)      0.1625
1180     (56230)      0.1500
1183     (56235)      0.1375
1170     (56217)      0.1250
1115     (56183)      0.1125

In [26]:
product_id = 56193
preds = predict(rules, {product_id})

print("Item = ", get_product_name(connection_mydb, product_id))

print("Recommandations : ")

for _,row in preds.iterrows():
    
    for id in row['consequents']:
        
        name = get_product_name(connection_mydb, int(id))
        print(id, name)

Item =  فرن-بني-HP
Recommandations :
56228 غسالة-أسود-LG
56247 غسالة-فضي-SONY
56230 غسالة-أسود-SONY
56235 مصفف شعر-أسود داكن-SONY
56217 غسالة-أسود-SAMSUNG
56183 براد-فضي-PANASONIC

In [29]:
def export_to_db(connection_mydb, rules):
  
  cursor = connection_mydb.cursor()
  
  sql = '''DROP TABLE IF EXISTS  custom_products_association'''
  
  cursor.execute(sql)
  
  sql = '''
  CREATE TABLE custom_products_association ( ID int(11) NOT NULL AUTO_INCREMENT,
    product_id_in int(11) NOT NULL,
    post_title_in text NOT NULL,
    product_id_out int(11) NOT NULL,
    post_title_out text NOT NULL,
    confidence double NOT NULL , PRIMARY KEY (ID))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
  '''
  
  cursor.execute(sql)
  
  connection_mydb.commit()
  
  for row in rules.itertuples():
    
    antecedents = row.antecedents
    
    consequents = row.consequents

    confidence = row.confidence*100
    
    for product_in in antecedents:
      
      post_title_in = get_product_name(connection_mydb,product_in)
      
      for product_out in consequents:
        
        post_title_out = get_product_name(connection_mydb,product_out)
        
        
        sql='''DELETE FROM custom_products_association where product_id_in=(%s) and
        product_id_out=(%s) and confidence <= (%s) '''
        
        params = (product_in,product_out,confidence )
        
        cursor.execute(sql,params)
        
        sql = '''SELECT * FROM custom_products_association where product_id_in=(%s) and
        product_id_out=(%s) and confidence >= (%s) '''
        
        params = (product_in,product_out,confidence )
        
        cursor.execute(sql,params)
        results = cursor.fetchall()

        must_add = True
        if results != None and len(results) > 0:
            must_add = False
        if must_add:
            sql = "INSERT INTO custom_products_association (product_id_in, post_title_in,product_id_out,post_title_out,confidence) VALUES (%s, %s,%s,%s,%s)"
            
            val = (product_in, post_title_in, product_out, post_title_out, confidence)
          
            cursor.execute(sql, val)
          
            connection_mydb.commit()

In [32]:
def start_generate_association_rules():

    connection_mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="",
        database="wp-ecommerce"
    )

    min_support = 0.001

    min_confidence = 0.001

    df = df_associated_products(connection_mydb)

    transactions_df = prepare_transactions(df)

    rules = generate_association_rules(transactions_df,min_support ,min_confidence)

    export_to_db(connection_mydb, rules)

In [33]:
start_generate_association_rules()

In [35]:
def get_recommandation_products_ids(connection_mydb, product_id):
    
    products_recommandations = pd.DataFrame(columns=['product_id', 'post_title', 'confidence'])
    
    cursor = connection_mydb.cursor(dictionary=True)
    
    sql = "SELECT * FROM custom_products_association WHERE product_id_in=(%s) order by confidence DESC"
    
    param = (product_id, )
    
    cursor.execute(sql, param)
    
    results = cursor.fetchall()
    
    for product in results:
        
        obj = {
            'product_id':product['product_id_out'],
            'post_title':product['post_title_out'],
            'confidence': round(product['confidence'], 2)
        }
        
        products_recommandations = pd.concat([products_recommandations, pd.DataFrame([obj])], ignore_index=True)
    
    return products_recommandations

product_id = 56306

product_name = get_product_name(connection_mydb, product_id)
print("Recommendations for ",product_id, product_name)

products_recommandations = get_product_name(connection_mydb, product_id)
products_recommandations

Recommendations for  56306 مجموعة العناية بالبشرة-BLVD 13

'مجموعة العناية بالبشرة-BLVD 13'